function l(b,a,c,d,e){b.s.Gb(b.kb,a,c,d,e)}function m(b,a,c,d){b.s.ca?l(b,a,c,d):b.s.Ce()._OnMessageFromDOM({type:"event",component:b.kb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.s.C(b.kb,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}function t(b){b.Rb||(b.s.od(b.Vd),b.Rb=!0)}function ba(b){b.Rb&&(b.s.Ne(b.Vd),b.Rb=!1)}window.Eb=class{constructor(b,a){this.s=b;this.kb=a;this.Rb=!1;this.Vd=()=>this.Da()}dd(){}Da(){}};
window.lf=class{constructor(){this.ad=-1}j(){-1!==this.ad&&(self.clearTimeout(this.ad),this.ad=-1)}};"use strict";class ca{constructor(b){this.Pb=b;this.Kc=!1;this.Sc=!0}}function da(b,a){const c=a.elementId,d=b.hd(c,a),e=new ca(d);b.Oa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Sc=!!a.isVisible;d.addEventListener("focus",()=>{u(b,"elem-focused",c)});d.addEventListener("blur",()=>{u(b,"elem-blurred",c)});b.ib&&document.body.appendChild(d)}
function v(b,a,c){q(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.Oa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Pb}function u(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}
window.ne=class extends self.Eb{constructor(b){super(b,"video");this.Oa=new Map;this.ib=!0;aa(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=w(this,a);this.kd(c);this.ib&&c.parentElement.removeChild(c);this.Oa.delete(a)}],["set-visible",a=>{if(this.ib){var c=this.Oa.get(a.elementId),d=c.Pb;c.Kc?d.style.display=a.isVisible?"":"none":c.Sc=!!a.isVisible}}],["update-position",a=>{if(this.ib){var c=this.Oa.get(a.elementId),d=c.Pb;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Kc||(c.Kc=!0,c.Sc&&(d.style.display=""))}}],["update-state",a=>{w(this,a.elementId);this.nd()}],["focus",a=>{const c=w(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);
v(this,"get-element",a=>a)}hd(){throw Error("required override");}kd(){}nd(){throw Error("required override");}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ha=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.af?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.ef+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ia=!1,ja=!1;function ka(){if(!ia){try{new Worker("blob://",{get type(){ja=!0}})}catch(b){}ia=!0}return ja}let A=new Audio;
const la={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ma(b){b=await pa(b);return(new TextDecoder("utf-8")).decode(b)}
function pa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let E=0;window.RealFile=window.File;const F=[],qa=new Map,ra=new Map;let sa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.gb=class b{constructor(a){this.ca=a.gf;this.xa=null;this.ba="";this.Ya=a.df;this.Bb={};this.Ra=this.va=null;this.Ob=[];this.J=this.ya=null;this.Oc=!1;this.Cd=0;this.pb=null;this.Xa=-1;this.Ve=()=>this.Je();this.Wa=[];this.B=a.Wd;this.Sb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ka()||(this.ca=!1);this.ca&&fa&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(x){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.sa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Fe(c));this.C("runtime","create-job-worker",()=>this.Ge());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.rd(a)):this.rd(a)}j(){this.wc();this.xa&&(this.xa=this.xa.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Ra&&(this.Ra.j(),this.Ra=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}re(){return ea&&"cordova"===this.B}sc(){const a=navigator.userAgent;return ea&&ua.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}pe(){return x}rc(){return x&&ua.has(this.B)}async rd(a){"macos-wkwebview"===this.B&&this.Oe();if("playable-ad"===this.B){this.sa=
self.c3_base64files;this.Vb={};await this.ye();for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Vb.hasOwnProperty(c)?a.$a[d]={af:!0,ef:this.Vb[c]}:this.sa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.sa[c]))}a.kc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.od(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.cf?this.ba=a.cf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.jf&&(this.Bb=a.jf);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ie(d));this.pb=new self.se(this);await wa(this.pb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.Ee(a,c.port2):await this.De(a,c.port2)}yc(a){a=this.Bb.hasOwnProperty(a)?this.Bb[a]:a.endsWith("/workermain.js")&&this.Bb.hasOwnProperty("workermain.js")?this.Bb["workermain.js"]:"playable-ad"===this.B&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async mc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Sb)return a=await this.Db(d.$e?a:this.Ya+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}qd(a){var c=this.ba,d=location.href,e=this.qa(),f=this.ja(),g=window.devicePixelRatio,h=b.eb(),k=a.qf,n=window.cr_previewImageBlobs||this.sa,p=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.nf||
"";a=a.Wd;var r=(new URLSearchParams(self.location.search)).has("debug"),D=this.pb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:r,ife:!!self.pf,jobScheduler:{inputPort:D.Nc,outputPort:D.Wc,maxNumWorkers:D.Se},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ya+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Ya+"opus.wasm.wasm",isFileProtocol:this.Sb,isiOSCordova:this.re(),isiOSWebView:this.sc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ee(a,c){const d=this.yc(a.hf);"preview"===this.B?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const n=p=>{this.va.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():k()};this.va.addEventListener("message",n);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.va=await this.mc(d,this.ba,{type:"module",name:"Runtime",$e:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.kc||[],g=a.$a;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,k=a.jc.length;h<k;++h){const n=
a.jc[h],p=n[0];if(p===a.bd||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.La(p)}this.va.postMessage(Object.assign(this.qd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.jc,mainProjectScript:a.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...xa(this.pb)]);this.Ob=F.map(h=>new h(this));this.pd();ya(this.ya);self.c3_callFunction=(h,k)=>{var n=this.ya;return n.s.md(n.kb,"js-invoke-function",
{name:h,params:k})};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Gb("runtime","go-to-last-error-script"))}async De(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ob=F.map(g=>new g(this));this.pd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.kc)){var e=[...a.kc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.La(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.bd;const f=a.jc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await y(h),"preview"!==this.B||d[g]||this.td(g,"main script did not run to completion")}catch(k){this.td(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await y(h);"preview"===this.B&&"object"!==typeof self.kf.mf?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.qd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:ta}),ya(this.ya),this.sd(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}td(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}sd(){this.Kb()}Kb(){const a=
window.Ye;a&&(a.parentElement.removeChild(a),window.Ye=null)}async Ge(){const a=await za(this.pb);return{outputPort:a,transferables:[a]}}Ce(){if(this.ca)throw Error("not available in worker mode");return this.Ra}Gb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}md(a,c,d,e,f){const g=sa++,h=new Promise((k,n)=>{ra.set(g,{resolve:k,reject:n})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.He(a);if("result"===c)this.Ke(a);else if("runtime-ready"===c)this.Le();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.sd();else throw Error(`unknown message '${c}'`);}He(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=qa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ke(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ra.get(c);d?e.resolve(a):e.reject(a);ra.delete(c)}C(a,
c,d){let e=qa.get(a);e||(e=new Map,qa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Cb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}pd(){for(const a of this.Ob)if("runtime"===a.kb){this.ya=a;return}throw Error("cannot find runtime DOM handler");}Ie(a){this.Gb("debugger","message",a)}Le(){for(const a of this.Ob)a.dd()}static eb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
va)}static ud(a){va=!!a}od(a){this.Wa.push(a);this.Dc()}Ne(a){a=this.Wa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Wa.splice(a,1);this.Wa.length||this.wc()}Dc(){-1===this.Xa&&this.Wa.length&&(this.Xa=requestAnimationFrame(this.Ve))}wc(){-1!==this.Xa&&(cancelAnimationFrame(this.Xa),this.Xa=-1)}Je(){this.Xa=-1;for(const a of this.Wa)a();this.Dc()}ea(a){this.ya.ea(a)}ia(a){this.ya.ia(a)}Cc(){this.ya.Cc()}Ib(a){this.ya.Ib(a)}qe(){return!!la["audio/webm; codecs=opus"]}async Pe(a){a=await this.md("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ue(a){this.Oc=!0;this.Cd=a}oe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ld(a){return!this.oe(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Sb&&this.ld(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Db(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Fe(a){const c=a.filename;switch(a.as){case "text":return await this.me(c);
case "buffer":return await this.Db(c);default:throw Error("unsupported type");}}gd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async me(a){a=await this.gd(a);return await ma(a)}xc(){if(B.length&&!(8<=E)){E++;var a=B.shift();this.ze(a.filename,a.ff,a.Ze)}}Db(a){return new Promise((c,d)=>{B.push({filename:a,ff:e=>{E--;this.xc();c(e)},Ze:e=>{E--;this.xc();d(e)}});this.xc()})}async ze(a,c,d){try{const e=
await this.gd(a),f=await pa(e);c(f)}catch(e){d(e)}}Oe(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ye(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.xe(c,d));await Promise.all(a)}async xe(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),
this.Vb[a]=c.str;else{let d=await this.Be(c);d||(d=this.Ae(c));this.sa[a]=d}}async Be(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ae(a){a=this.Me(a);return this.we(a.data,a.bf)}Me(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{bf:a,data:d}}we(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.gb;
function Aa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};
function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}
function Ga(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ha(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ga(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ia(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ja=new Set(["input","textarea","datalist","select"]),Ka=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ka.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ha(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function ya(b){b.Bd=!0;b.Tc=b.s.qa();b.qb=b.s.ja()}async function Na(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Oa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Pa(b){return await self.C3_GetSvgImageSize(b.blob)}function Qa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ra(b){self.setTimeout(()=>{b.Ad=!0},1E3);"cordova"===b.s.B?(document.addEventListener("pause",()=>Sa(b,!0)),document.addEventListener("resume",()=>Sa(b,!1))):document.addEventListener("visibilitychange",()=>Sa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ma)}}
function Ta(b){b.wd||(b.wd=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ua(b){b.vd||(b.vd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Va(b){await Ea(b.url)}
function Wa(b,a){b.Dd=a.message;-1===b.Ic&&(b.Ic=setTimeout(()=>{b.Ic=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Dd)},250))}function L(b){if(!b.$){var a=H.eb();a&&"any"!==b.Zc&&Xa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ja()})}}function Ya(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:H.eb(),innerWidth:b.qa(),innerHeight:b.ja()})}
function Sa(b,a){a?b.s.wc():b.s.Dc();l(b,"visibilitychange",{hidden:a})}function Za(b,a,c){"Backspace"===c.key&&K(c);if(!b.$){var d=Ba.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function $a(b,a,c,d){b.$||Aa(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function bb(b){window!==window.top&&window.focus();cb(b.target)&&document.activeElement&&!cb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.vb);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),$a(b,d,c,Ca),b.vb=c.buttons)}}
function db(b,a,c){if(!b.$&&!Aa(c)){var d=b.vb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.vb=c.buttons;$a(b,c.type,c,Ca)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function eb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function fb(b,a,c,d){const e=b.qa(),f=b.ja();b.Za=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.eb()}):10>d&&hb(b,e,f,d+1)}
function hb(b,a,c,d){-1!==b.Za&&clearTimeout(b.Za);b.Za=setTimeout(()=>fb(b,a,c,d),48)}
function Xa(b){b=b.Zc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function cb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Cb(class extends self.Eb{constructor(b){super(b,"runtime");this.Id=!0;this.Bd=!1;this.Za=-1;this.Zc="any";this.vd=this.wd=!1;this.ec=document.createElement("div");this.ec.className="c3-screen-reader-text";this.ec.setAttribute("aria-live","polite");document.body.appendChild(this.ec);this.Ga=null;this.$=!1;this.Dd="";this.Ic=-1;this.Ad=!1;this.Tc=b.qa();this.qb=b.ja();this.da=this.Ab=0;b.C("canvas","update-size",d=>{var e=this.s;e.Oc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Id&&(e.style.display="",this.Id=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Na(d));b.C("runtime","raster-svg-image",d=>Oa(d));b.C("runtime","get-svg-image-size",
d=>Pa(d));b.C("runtime","set-target-orientation",d=>{this.Zc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Qa(d));b.C("runtime","go-to-script",d=>Qa(d));b.C("runtime","before-start-ticking",()=>Ra(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var e=this.Ga;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ga&&(this.Ga.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ta(this));b.C("runtime","enable-device-motion",()=>Ua(this));b.C("runtime","add-stylesheet",d=>Va(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ec.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.J.style.display="";this.s.ue(d.duration)});b.C("runtime","export-to-video-progress",d=>Wa(this,d));b.C("runtime","exported-to-video",d=>{window.Xe({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Xe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ia(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",
K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.vb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Bd){var d=this.qa();var e=this.ja();if(this.s.rc()){if(this.Ad){if(this.Tc===
d&&e<this.qb){this.Ab=this.qb-e;eb(this,this.qb,this.Ab);d=void 0;break a}0<this.Ab&&(this.Ab=0,eb(this,e,this.Ab))}this.Tc=d;this.qb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.eb()});this.s.sc()&&(-1!==this.Za&&clearTimeout(this.Za),fb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>Ya(this,d));window.addEventListener("webkitfullscreenerror",d=>Ya(this,d));window.addEventListener("mozfullscreenerror",d=>Ya(this,d));if(b.sc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ia(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.ud(!0),L(this)):"exited-fullscreen"===d?(H.ud(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Sa=new Set;this.Xb=new WeakSet;this.wa=!1}dd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},Da);this.vb=0});window.addEventListener("focusin",a=>{a=a.target;(Ja.has(a.tagName.toLowerCase())||Ia(a))&&l(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>Za(this,"keydown",a));window.addEventListener("keyup",a=>Za(this,"keyup",a));window.addEventListener("dblclick",a=>$a(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{bb(a);M(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{bb(a);db(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>db(this,"pointermove",a)),window.addEventListener("mouseup",a=>db(this,"pointerup",a)),window.addEventListener("touchstart",a=>{bb(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.Cc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.pe()&&!this.s.rc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{eb(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.s.qa()}ja(){return this.s.ja()}Cc(){var b=
[...this.Sa];this.Sa.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Xb.has(a)||this.Sa.add(a)})}ea(b){if("function"!==typeof b.play)throw Error("missing play function");this.Xb.delete(b);let a;try{a=b.play()}catch(c){this.Sa.add(b);return}a&&a.catch(()=>{this.Xb.has(b)||this.Sa.add(b)})}ia(b){this.Sa.delete(b);this.Xb.add(b)}Ib(b){this.wa=!!b}});"use strict";
async function wa(b){if(b.Qe)throw Error("already initialised");b.Qe=!0;var a=b.za.yc(("playable-ad"===b.za.B?b.za.Ya:"")+"dispatchworker.js");b.Hc=await b.za.mc(a,b.jb,{name:"DispatchWorker"});a=new MessageChannel;b.Nc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Wc=await za(b)}function xa(b){return[b.Nc,b.Wc]}
async function za(b){const a=b.Jd.length;var c=b.za.yc(("playable-ad"===b.za.B?b.za.Ya:"")+"jobworker.js");c=await b.za.mc(c,b.jb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Jd.push(c);return e.port1}
self.se=class{constructor(b){this.za=b;this.jb=b.ba;this.jb="preview"===b.B?this.jb+"workers/":this.jb+b.Ya;this.Se=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Jd=[];this.Wc=this.Nc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.gb({gf:!0,hf:"workermain.js",$a:["scripts/c3runtime.js"],jc:[],bd:"",df:"scripts/",kc:[],Wd:"html5"}));"use strict";const ib=180/Math.PI;
async function jb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.$c=a.timeScaleMode;b.Od=["equalpower","HRTF","soundfield"][a.panningModel];b.zd=["linear","inverse","exponential"][a.distanceModel];b.Pd=a.refDistance;b.Nd=a.maxDistance;b.Rd=a.rolloffFactor;if(b.s.Oc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Cd)});else{var c={latencyHint:a.latencyHint};b.Ud||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.fa);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,n=a.pos,p=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Kd=g.slice(0);mb(b,g);try{b.R=await nb(b,c,d,e,g,f);if(p){P(b.R,!0);var r=b.R,D=p.innerAngle,na=p.outerAngle,oa=p.outerGain;if(r.ob){ob(r,p.x,p.y,p.z,p.angle);var G=self.ab.ve;r.ta[0]!==G(D)&&
(r.ta[0]=G(D),r.F.coneInnerAngle=G(D));r.ta[1]!==G(na)&&(r.ta[1]=G(na),r.F.coneOuterAngle=G(na));r.ta[2]!==oa&&(r.ta[2]=oa,r.F.coneOuterGain=oa)}p.hasOwnProperty("uid")&&(b.R.ra=p.uid)}else"number"===typeof C&&0!==C?(Q(b.R,!0),pb(b.R,C)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,n,z)}catch(Cb){console.error("[Construct] Audio: error starting playback: ",Cb);return}finally{c=g.join(" ");d=b.xb.get(c);if(!d)throw Error("expected pending tag");d.cd--;0===d.cd&&(d.resolve(),b.xb.delete(c))}t(b)}
async function qb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const h of R(b,c))if(!h.Qa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ja=d;h.Pa=g;h.Td=a}S(b)}async function sb(b,a){const c=a.tags;a=a.rate;await rb(b,c);for(const d of R(b,c))d.na!==a&&(d.na=a,d.Ea())}async function tb(b,a){const c=a.tags;a=a.pos;await rb(b,c);for(const d of R(b,c))d.tc(a)}
async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function wb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.be(b,...e);else if("delay"===c)d=new self.$d(b,...e);else if("convolution"===c){var g=d=new self.Zd(b,f.ka,...e),h=a.bufferType;g.xd=a.bufferOriginalUrl;g.yd=h}else if("flanger"===c)d=new self.ce(b,...e);else if("phaser"===
c)d=new self.ee(b,...e);else if("gain"===c)d=new self.de(b,...e);else if("stereopan"===c)d=new self.ge(b,...e);else if("tremolo"===c)d=new self.he(b,...e);else if("ringmod"===c)d=new self.fe(b,...e);else if("distortion"===c)d=new self.ae(b,...e);else if("compressor"===c)d=new self.Yd(b,...e);else if("analyser"===c)d=new self.Xd(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let n=g.ma.get(h);n||(n=[],g.ma.set(h,n));d.Hd=n.length;d.Yc=h;n.push(d);xb(g,h)}yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ma.values())for(const g of f)g.j();b.ma.clear();b.hc=a.timeScale;b.Jc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.fa[e]=d[e];b.g.listener.setOrientation(...b.fa)}b.wa=a.isSilent;b.s.Ib(b.wa);b.Wb=a.masterVolume;b.Na.gain.value=
b.Wb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>wb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));S(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Gd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.Gb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Db(d)),b.Gd=!0);await c}catch(c){Db(c)}}
function kb(b){b.Qb||(b.Mc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Qb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.la)if(g.cb()===c)return await Fb(g),g;if(f)return null;if(e&&(b.ac||b.Fd)){f=0;for(let h=0,k=b.la.length;h<k;++h)g=b.la[h],b.la[f]=g,g.Ba()?g.j():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.Ud;e&&f&&(b.Fd=!0);c=!e||b.ac||f?new self.ke(b,a,c,d,e,f):new self.ie(b,a,c,d,e);b.la.push(c);await Fb(c);b.Md.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Md.add(a));return c}
function Gb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Hb(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].N():b.pa()}function xb(b,a){a=a.toLowerCase();let c=b.pa();var d=b.ma.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.pa()):e.U(d[f+1].N())}}for(const f of Ib(b,a))d=c,e=f.ga||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Uc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*Ib(b,a){if(a)for(const c of b.H)Gb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Jb(b,a,c){return c?b.s.Pe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Kb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Gb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function nb(b,a,c,d,e,f){for(const g of b.H)if(g.cb()===c&&(g.lc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ec?new self.je(a.u,a,e):new self.le(a.u,a,e);b.H.push(e);return e}
function mb(b,a){a=a.join(" ");let c=b.xb.get(a);if(!c){let d=null;c={cd:0,promise:new Promise(e=>d=e),resolve:d};b.xb.set(a,c)}c.cd++}function rb(b,a){return(b=b.xb.get((0===a.length?b.Kd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ma.size)t(b);else for(const a of b.H)if(!a.I&&!a.O()){t(b);break}}function Lb(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function yb(b){b.Pc||(b.Pc=!0,Promise.resolve().then(()=>Mb(b)))}
function Mb(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.bb());l(b,"fxstate",{fxstate:a});b.Pc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,n=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],f=d.orient,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],e.setPosition(...b.Ua),e.setOrientation(...b.Ta),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),pb(b,d));c.Play(k,n,p,0);a.isPlaying||c.fb();c.Ac(a)}}}function Db(b){console.error("[Audio] Offline rendering error: ",b)}
self.ab=class extends self.Eb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Qb=this.Mc=!1;this.Aa=()=>{if(!this.Mc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Qb&&(this.Mc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Qb=!1)}};this.la=[];this.H=[];this.R=null;this.Kd=[];this.Md=new Set;this.Ld=-1;this.xb=new Map;this.Wb=1;this.wa=!1;this.$c=0;this.hc=1;this.Jc=0;this.Od="HRTF";this.zd="inverse";this.Pd=600;this.Nd=1E4;this.Rd=1;this.aa=[0,0,0];this.fa=[0,0,-1,0,1,0];this.Fd=this.ac=!1;this.Ud=this.s.qe();this.ma=new Map;this.Ma=new Set;this.Gd=this.Pc=!1;this.Uc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Uc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(Hb(this,this.Uc))};this.Nb=null;self.C3Audio_GetOutputStream=()=>{this.Nb||(this.Nb=this.g.createMediaStreamDestination(),this.Na.connect(this.Nb));return this.Nb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>jb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.fb():d.Hb();S(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.Wb=a.vol;this.Na.gain.value=this.Wb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Nb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.s.Ib(this.wa);for(const c of this.H)c.Lb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.uc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.la)a.j();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.vc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ma.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);yb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ma.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ma.delete(a);xb(this,a)}}],["tick",a=>{this.hc=a.timeScale;this.Jc=a.gameTime;this.Ld=a.tickCount;if(0!==this.$c)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.fa[0]!==
c[0]||this.fa[1]!==c[1]||this.fa[2]!==c[2]||this.fa[3]!==c[3]||this.fa[4]!==c[4]||this.fa[5]!==c[5])){for(let d=0;6>d;++d)this.fa[d]=c[d];this.g.listener.setOrientation(...this.fa)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&ob(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}pa(){return this.Na}Fb(){return this.wa}ea(b){this.s.ea(b)}ia(b){this.s.ia(b)}Da(){for(var b of this.Ma)b.Da();
b=this.g.currentTime;for(var a of this.H)a.Da(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.bb());l(this,"state",{tickCount:this.Ld,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.Yc,index:c.Hd,peak:c.Va,rms:c.Qd,binCount:c.l.frequencyBinCount,freqBins:c.Ed}))});0===a.length&&0===this.Ma.size&&ba(this)}static ve(b){return b*ib}static jd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static te(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.gb.Cb(self.ab);"use strict";function Fb(b){b.Ub||(b.Ub=b.zc());return b.Ub}self.ed=class{constructor(b,a,c,d,e){this.u=b;this.Ue=a;this.Ia=c;this.T=d;this.Re=e;this.Ec="";this.Ub=null}j(){this.Ub=this.u=null}zc(){}W(){return this.u.W()}oc(){return this.Ue}cb(){return this.Ia}nc(){return this.T}Ba(){return this.Re}ha(){}};"use strict";
self.ie=class extends self.ed{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ec="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.rb=this.sb=null;this.M.addEventListener("canplaythrough",()=>!0);this.wb=this.W().createGain();this.ub=null;this.M.addEventListener("canplay",()=>{this.sb&&(this.sb(),this.rb=this.sb=null);!this.ub&&this.M&&(this.ub=this.W().createMediaElementSource(this.M),this.ub.connect(this.wb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.rb&&(this.rb(f),this.rb=this.sb=null)})}j(){Kb(this.u,this);this.wb.disconnect();this.wb=null;this.ub.disconnect();this.ub=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}zc(){return new Promise((b,a)=>{this.sb=b;this.rb=a;this.M.src=this.Ia})}V(){return this.M}ha(){return this.M.duration}};"use strict";
async function Ob(b){if(b.Fa)return b.Fa;var a=b.u.s;if("cordova"===a.B&&a.ld(b.Ia)&&a.Sb)b.Fa=await a.Db(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Pb(b){if(b.ka)return b.ka;b.ka=await Jb(b.u,b.Fa,b.Te);b.Fa=null}
self.ke=class extends self.ed{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ec="webaudio";this.ka=this.Fa=null;this.Te=!!f}j(){Kb(this.u,this);this.ka=this.Fa=null;super.j()}async zc(){try{await Ob(this),await Pb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}ha(){return this.ka?this.ka.duration:0}};"use strict";let Qb=0;
function P(b,a){a=!!a;b.ob!==a&&(b.ob=a,b.ob?(Q(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.u.Od,b.F.distanceModel=b.u.zd,b.F.refDistance=b.u.Pd,b.F.maxDistance=b.u.Nd,b.F.rolloffFactor=b.u.Rd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.pa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.pa())))}
function Q(b,a){a=!!a;b.Tb!==a&&(b.Tb=a,b.Tb?(P(b,!1),b.ga=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ga),b.ga.connect(b.pa())):(b.ga.disconnect(),b.ga=null,b.G.disconnect(),b.G.connect(b.pa())))}function pb(b,a){b.Tb&&b.Xc!==a&&(b.ga.pan.value=a,b.Xc=a)}function T(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.Pa=-1;b.G.gain.value=b.pc()}function Nb(b,a){a=!!a;b.Qa!==a&&(b.Qa=a,b.Lb())}
function ob(b,a,c,d,e){if(b.ob){var f=b.Ua,g=b.Ta,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Rc?b.u.Jc:performance.now()/1E3}
self.fd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Mb=Qb++;this.G=this.W().createGain();this.G.connect(this.pa());this.F=null;this.ob=!1;this.Ua=[0,0,0];this.Ta=[0,0,0];this.ta=[0,0,0];this.ga=null;this.Tb=!1;this.Xc=0;this.I=!0;this.Y=this.ua=this.K=!1;this.Ja=1;this.Qa=!1;this.na=1;b=this.u.$c;this.Rc=1===b&&!this.Ba()||2===b;this.Pa=this.ra=-1;this.Td=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ga&&(this.ga.disconnect(),this.ga=null);this.G.disconnect();
this.G=null}W(){return this.u.W()}pa(){return Hb(this.u,0<this.oa.length?this.oa[0]:"")}oc(){return this.P.oc()}cb(){return this.P.cb()}nc(){return this.P.nc()}Ba(){return this.P.Ba()}O(){}lc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ka(){}ha(){return this.P.ha()}Play(){}Ca(){}fb(){}Hb(){}Da(b){-1!==this.Pa&&b>=this.Pa&&(this.Pa=-1,this.Td&&this.Ca(),Lb(this.u,"fade-ended",this.oa,this.Mb))}pc(){const b=this.Ja;return isFinite(b)?b:0}Fb(){return this.u.Fb()}Lb(){}uc(){}Ea(){}tc(){}vc(){}qc(){}bb(){var b=
this.Mb,a=this.oa,c=this.ha(),d=-1===this.Pa?this.Ja:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ua,orient:this.Ta,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ka(),playbackRate:this.na,uid:this.ra,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Qa,resumePosition:this.qc(),pan:f,stereoPan:this.ga?
this.Xc:null}}Ac(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Ea());Nb(this,b.isMuted)}};"use strict";
self.je=class extends self.fd{constructor(b,a,c){super(b,a,c);this.P.wb.connect(this.G);this.P.onended=()=>this.Bc()}j(){this.Ca();this.P.wb.disconnect();super.j()}V(){return this.P.V()}Bc(){this.I=!0;this.ra=-1;Lb(this.u,"ended",this.oa,this.Mb)}O(){return this.V().ended}lc(){return this.I?!0:this.O()}Ka(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.cb()}' to position '${c}': `,e)}this.u.ea(d);this.K=this.I=!1;this.Y=b;this.na=1}Ca(){const b=this.V();b.paused||b.pause();this.u.ia(b);this.I=!0;this.K=!1;this.ra=-1}fb(){if(!(this.K||this.I||this.O())){var b=this.V();b.paused||b.pause();this.u.ia(b);this.K=!0}}Hb(){!this.K||this.I||this.O()||(this.u.ea(this.V()),this.K=!1)}Lb(){this.V().muted=this.Qa||this.Fb()}uc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Ea(){let b=this.na;this.Rc&&(b*=this.u.hc);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}tc(b){if(!this.I&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}qc(){return this.Ka()}vc(b){b?this.IsPlaying()?(this.V().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.u.ea(this.V()),this.ua=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.hb=null}
self.le=class extends self.fd{constructor(b,a,c){super(b,a,c);this.o=null;this.Zb=d=>this.Bc(d);this.Lc=!0;this.hb=null;this.S=this.$b=this.bc=0;this.Vc=1}j(){this.Ca();V(this);this.Zb=null;super.j()}Bc(b){this.K||this.ua||b.target!==this.hb||(this.I=this.Lc=!0,this.ra=-1,V(this),Lb(this.u,"ended",this.oa,this.Mb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Lc}lc(){return!this.o||this.I?!0:this.O()}Ka(){let b;b=this.K?this.S:this.$b+(U(this)-this.bc)*this.na;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Vc=1;T(this,a);V(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ka;this.o.connect(this.G);this.hb=this.o;this.o.onended=this.Zb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Lc=!1;this.Y=b;this.na=1;this.bc=U(this);this.$b=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.ra=-1}fb(){this.K||this.I||this.O()||(this.S=this.Ka(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.I||this.O()||(V(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Zb,this.o.loop=this.Y,T(this,this.Ja),this.Ea(),this.o.start(0,this.S),this.bc=U(this),this.$b=this.S,this.K=!1)}pc(){return super.pc()*this.Vc}Lb(){this.Vc=this.Qa||this.Fb()?0:1;T(this,this.Ja)}uc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ea(){let b=this.na;this.Rc&&(b*=this.u.hc);this.o&&(this.o.playbackRate.value=b)}tc(b){this.I||this.O()||(this.K?this.S=b:(this.fb(),this.S=
b,this.Hb()))}qc(){return this.S}vc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Ka(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ua=!1:this.ua&&(V(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Zb,this.o.loop=this.Y,T(this,this.Ja),this.Ea(),this.o.start(0,this.S),this.bc=U(this),this.$b=this.S,this.ua=!1)}Ac(b){super.Ac(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.W();this.Hd=-1;this.T=this.Yc="";this.m=null}j(){this.g=null}N(){}U(){}bb(){return{type:this.T,tag:this.Yc,params:this.m}}}
self.be=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.$d=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.tb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.mb=W(this);this.mb.gain.value=c;this.v.connect(this.tb);this.v.connect(this.h);this.tb.connect(this.i);this.tb.connect(this.X);this.X.connect(this.mb);this.mb.connect(this.tb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.tb.disconnect();
this.X.disconnect();this.mb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.ab.jd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.mb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.Zd=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.yd=this.xd="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.lb=this.g.createConvolver();this.lb.normalize=c;this.lb.buffer=a;this.v.connect(this.lb);this.v.connect(this.h);this.lb.connect(this.i)}j(){this.v.disconnect();this.lb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}bb(){const b=super.bb();b.bufferOriginalUrl=this.xd;b.bufferUrl="";b.bufferType=this.yd;return b}};
self.ce=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.nb=W(this);this.nb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.nb);this.nb.connect(this.X);this.A.connect(this.L);
this.L.connect(this.X.delayTime);this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.X.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.nb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.nb.gain,a/100,c,d)}}};
self.ee=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.A.frequency,a,c,d)}}};self.de=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.ab.jd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ge=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.he=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.fe=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.zb=W(this);this.zb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.zb.gain);this.A.start(0);this.v.connect(this.zb);this.v.connect(this.h);this.zb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.zb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.ae=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=W(this);this.dc=W(this);this.cc=W(this);b=d;.01>b&&(b=.01);this.dc.gain.value=b;this.cc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.ic=this.g.createWaveShaper();this.Fc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Fc[32768+e]=f,this.Fc[32768-
e-1]=-f;this.ic.curve=this.Fc;this.v.connect(this.dc);this.v.connect(this.h);this.dc.connect(this.ic);this.ic.connect(this.cc);this.cc.connect(this.i)}j(){this.v.disconnect();this.dc.disconnect();this.ic.disconnect();this.cc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Yd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Xd=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Ed=new Float32Array(this.l.frequencyBinCount);this.Sd=new Uint8Array(a);this.Qd=this.Va=0;b=this.u;b.Ma.add(this);S(b)}j(){this.u.Ma.delete(this);this.l.disconnect();super.j()}Da(){this.l.getFloatFrequencyData(this.Ed);this.l.getByteTimeDomainData(this.Sd);const b=this.l.fftSize;let a=this.Va=0;for(var c=0;c<b;++c){let d=(this.Sd[c]-
128)/128;0>d&&(d=-d);this.Va<d&&(this.Va=d);a+=d*d}c=self.ab.te;this.Va=c(this.Va);this.Qd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Rb(b,a){a=a.type;let c=!0;0===a?c=await Sb():1===a&&(c=await Tb());l(b,"permission-result",{type:a,result:c})}
async function Sb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Tb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.gb.Cb(class extends self.Eb{constructor(b){super(b,"touch");q(this,"request-permission",a=>Rb(this,a))}});"use strict";
async function Ub(b,a){b.Qc=a.isInWorker;a=document.createElement("video");b.fc=!!a.requestVideoFrameCallback&&!b.s.rc();const c=!!self.createImageBitmap;b.yb=b.Qc||c;return{postImageBitmaps:b.yb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Vb(b,a){if(!b.Gc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Vb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Gc.has(a)||u(b,"playback-event",c,{type:d})}
self.gb.Cb(class extends self.ne{constructor(b){super(b);this.yb=this.fc=this.Qc=this.ib=!1;this.Yb=this.We=0;this.Gc=new WeakSet;q(this,"init",a=>Ub(this,a));v(this,"play",a=>{this.ea(a)});v(this,"pause",a=>{this.ia(a);a.pause()});v(this,"set-source",(a,c)=>{a.src=c.src;a.load()});v(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});v(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});v(this,"set-looping",(a,c)=>{a.loop=c.isLooping});v(this,"set-muted",(a,c)=>{a.muted=c.isMuted});v(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>w(this,a)}ea(b){this.s.ea(b);this.yb&&this.fc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Vb(this,b)))}ia(b){this.s.ia(b);this.yb&&this.fc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}hd(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ea(c);this.Yb++;t(this);return c}nd(){}kd(b){this.ia(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.Yb=Math.max(this.Yb-1,0);0===this.Yb&&ba(this);this.Gc.add(b)}Da(){const b={},a={sequenceNumber:this.We++,videoData:b},c=[],d=[];for(const [e,f]of this.Oa.entries()){const g=f.Pb,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.yb)if(this.fc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.Qc?l(this,"state",a,!1,c):m(this,"state",a)})}});
