function l(b,a,c,d,e){b.s.Gb(b.mb,a,c,d,e)}function m(b,a,c,d){b.s.ca?l(b,a,c,d):b.s.Fe()._OnMessageFromDOM({type:"event",component:b.mb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.s.C(b.mb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Sb||(b.s.sd(b.Yd),b.Sb=!0)}function aa(b){b.Sb&&(b.s.Qe(b.Yd),b.Sb=!1)}window.eb=class{constructor(b,a){this.s=b;this.mb=a;this.Sb=!1;this.Yd=()=>this.Ea()}hd(){}Ea(){}};
window.nf=class{constructor(){this.ed=-1}j(){-1!==this.ed&&(self.clearTimeout(this.ed),this.ed=-1)}};"use strict";class ba{constructor(b){this.Qb=b;this.Oc=!1;this.Wc=!0}}function ca(b,a){const c=a.elementId,d=b.md(c,a),e=new ba(d);b.Pa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Wc=!!a.isVisible;d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.kb&&document.body.appendChild(d)}
function w(b,a,c){n(b,a,d=>{const e=x(b,d.elementId);return c(e,d)})}function x(b,a){b=b.Pa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Qb}function v(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}
window.qe=class extends self.eb{constructor(b){super(b,"video");this.Pa=new Map;this.kb=!0;t(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=x(this,a);this.od(c);this.kb&&c.parentElement.removeChild(c);this.Pa.delete(a)}],["set-visible",a=>{if(this.kb){var c=this.Pa.get(a.elementId),d=c.Qb;c.Oc?d.style.display=a.isVisible?"":"none":c.Wc=!!a.isVisible}}],["update-position",a=>{if(this.kb){var c=this.Pa.get(a.elementId),d=c.Qb;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Oc||(c.Oc=!0,c.Wc&&(d.style.display=""))}}],["update-state",a=>{x(this,a.elementId);this.rd()}],["focus",a=>this.Ec(a)],["set-css-style",a=>{const c=x(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{x(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{x(this,a.elementId).removeAttribute(a.name)}]]);w(this,"get-element",
a=>a)}md(){throw Error("required override");}od(){}rd(){throw Error("required override");}Ec(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function A(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.cf?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.gf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let B=new Audio;
const ka={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const na=[];let E=0;window.RealFile=window.File;const F=[],qa=new Map,ra=new Map;let sa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.wa=class b{constructor(a){this.ca=a.jf;this.ya=null;this.ba="";this.Za=a.ff;this.Db={};this.Sa=this.va=null;this.Pb=[];this.J=this.za=null;this.Sc=!1;this.Fd=0;this.rb=null;this.Ya=-1;this.Xe=()=>this.Me();this.Xa=[];this.v=a.Zd;this.Tb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ca=!1);this.ca&&ea&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.sa=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Ie(c));this.C("runtime","create-job-worker",()=>this.Je());"cordova"===this.v?document.addEventListener("deviceready",
()=>this.vd(a)):this.vd(a)}j(){this.xc();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Sa&&(this.Sa.j(),this.Sa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}ue(){return da&&"cordova"===this.v}tc(){const a=navigator.userAgent;return da&&ua.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}se(){return y}sc(){return y&&ua.has(this.v)}async vd(a){"macos-wkwebview"===this.v&&this.Hc({type:"ready"});if("playable-ad"===
this.v){this.sa=self.c3_base64files;this.Wb={};await this.Be();for(let d=0,e=a.ab.length;d<e;++d){var c=a.ab[d];this.Wb.hasOwnProperty(c)?a.ab[d]={cf:!0,gf:this.Wb[c]}:this.sa.hasOwnProperty(c)&&(a.ab[d]=URL.createObjectURL(this.sa[c]))}a.lc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.sd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.ef?this.ba=a.ef:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),
-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.lf&&(this.Db=a.lf);c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Le(d));this.rb=new self.ve(this);await xa(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.He(a,c.port2):await this.Ge(a,c.port2)}zc(a){a=this.Db.hasOwnProperty(a)?this.Db[a]:a.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:"playable-ad"===this.v&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async nc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Tb)return a=await this.Eb(d.bf?a:this.Za+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}ud(a){var c=this.ba,d=location.href,e=this.qa(),f=this.ja(),g=window.devicePixelRatio,h=b.hb(),k=a.tf,p=window.cr_previewImageBlobs||this.sa,q=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.rf||
"";a=a.Zd;var r=(new URLSearchParams(self.location.search)).has("debug"),D=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:r,ife:!!self.sf,jobScheduler:{inputPort:D.Rc,outputPort:D.$c,maxNumWorkers:D.Ue},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Za+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Za+"opus.wasm.wasm",isFileProtocol:this.Tb,isiOSCordova:this.ue(),isiOSWebView:this.tc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async He(a,c){const d=this.zc(a.kf);"preview"===this.v?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const p=q=>{this.va.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():k()};this.va.addEventListener("message",p);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.va=await this.nc(d,this.ba,{type:"module",name:"Runtime",bf:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.lc||[],g=a.ab;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.v)for(let h=0,k=a.kc.length;h<k;++h){const p=
a.kc[h],q=p[0];if(q===a.fd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Ma(q)}this.va.postMessage(Object.assign(this.ud(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.kc,mainProjectScript:a.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ya(this.rb)]);this.Pb=F.map(h=>new h(this));this.td();za(this.za);self.c3_callFunction=(h,k)=>{var p=this.za;return p.s.qd(p.mb,"js-invoke-function",
{name:h,params:k})};"preview"===this.v&&(self.goToLastErrorScript=()=>this.Gb("runtime","go-to-last-error-script"))}async Ge(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=F.map(g=>new g(this));this.td();var d=a.ab.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.lc)){var e=[...a.lc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ma(g)));await Promise.all(d.map(g=>A(g)));d=self.C3_ProjectScriptsStatus;e=a.fd;const f=a.kc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await A(h),"preview"!==this.v||d[g]||this.xd(g,"main script did not run to completion")}catch(k){this.xd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await A(h);"preview"===this.v&&"object"!==typeof self.mf.pf?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.ud(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:ta}),za(this.za),this.wd(),this.Sa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Sa,a))}xd(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}wd(){this.Kb()}Kb(){const a=
window.$e;a&&(a.parentElement.removeChild(a),window.$e=null)}async Je(){const a=await Aa(this.rb);return{outputPort:a,transferables:[a]}}Fe(){if(this.ca)throw Error("not available in worker mode");return this.Sa}Gb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}qd(a,c,d,e,f){const g=sa++,h=new Promise((k,p)=>{ra.set(g,{resolve:k,reject:p})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ke(a);if("result"===c)this.Ne(a);else if("runtime-ready"===c)this.Oe();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.wd();else throw Error(`unknown message '${c}'`);}Ke(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=qa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ne(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ra.get(c);d?e.resolve(a):e.reject(a);ra.delete(c)}C(a,
c,d){let e=qa.get(a);e||(e=new Map,qa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static bb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}td(){for(const a of this.Pb)if("runtime"===a.mb){this.za=a;return}throw Error("cannot find runtime DOM handler");}Le(a){this.Gb("debugger","message",a)}Oe(){for(const a of this.Pb)a.hd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
va)}static Lb(a){va=!!a}sd(a){this.Xa.push(a);this.Gc()}Qe(a){a=this.Xa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Xa.splice(a,1);this.Xa.length||this.xc()}Gc(){-1===this.Ya&&this.Xa.length&&(this.Ya=requestAnimationFrame(this.Xe))}xc(){-1!==this.Ya&&(cancelAnimationFrame(this.Ya),this.Ya=-1)}Me(){this.Ya=-1;for(const a of this.Xa)a();this.Gc()}ea(a){this.za.ea(a)}ia(a){this.za.ia(a)}Fc(){this.za.Fc()}Ib(a){this.za.Ib(a)}te(){return!!ka["audio/webm; codecs=opus"]}async Re(a){a=await this.qd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}xe(a){this.Sc=!0;this.Fd=a}re(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}pd(a){return!this.re(a)}async Ma(a){return"cordova"===this.v&&(a.startsWith("file:")||this.Tb&&this.pd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ie(a){const c=a.filename;switch(a.as){case "text":return await this.pe(c);
case "buffer":return await this.Eb(c);default:throw Error("unsupported type");}}ld(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async pe(a){a=await this.ld(a);return await la(a)}yc(){if(na.length&&!(8<=E)){E++;var a=na.shift();this.Ce(a.filename,a.hf,a.af)}}Eb(a){return new Promise((c,d)=>{na.push({filename:a,hf:e=>{E--;this.yc();c(e)},af:e=>{E--;this.yc();d(e)}});this.yc()})}async Ce(a,c,d){try{const e=
await this.ld(a),f=await ma(e);c(f)}catch(e){d(e)}}Hc(a){if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Be(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Ae(c,d));await Promise.all(a)}async Ae(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.Wb[a]=c.str;else{let d=
await this.Ee(c);d||(d=this.De(c));this.sa[a]=d}}async Ee(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}De(a){a=this.Pe(a);return this.ze(a.data,a.df)}Pe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{df:a,data:d}}ze(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.wa;
function Ba(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ca=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Da={dispatchUserScriptEvent:!0},Ea={dispatchRuntimeEvent:!0};
function Fa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ga(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ga(b)}finally{URL.revokeObjectURL(b)}}
function Ha(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ia(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ha(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ja(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ka=new Set(["input","textarea","datalist","select"]),La=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&La.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ma(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ia(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Na=!1;document.addEventListener("pause",()=>Na=!0);document.addEventListener("resume",()=>Na=!1);function za(b){b.Ed=!0;b.Xc=b.s.qa();b.sb=b.s.ja()}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Qa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ra(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Sa(b){self.setTimeout(()=>{b.Dd=!0},1E3);"cordova"===b.s.v?(document.addEventListener("pause",()=>Ta(b,!0)),document.addEventListener("resume",()=>Ta(b,!1))):document.addEventListener("visibilitychange",()=>Ta(b,document.hidden));return{isSuspended:!(!document.hidden&&!Na)}}
function Ua(b){b.zd||(b.zd=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Va(b){b.yd||(b.yd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Wa(b){await Fa(b.url)}
function Xa(b,a){b.Gd=a.message;-1===b.Mc&&(b.Mc=setTimeout(()=>{b.Mc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Gd)},250))}function L(b){if(!b.$){var a=H.hb();a&&"any"!==b.cd&&Ya(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ja()})}}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:H.hb(),innerWidth:b.qa(),innerHeight:b.ja()})}
function Ta(b,a){a?b.s.xc():b.s.Gc();l(b,"visibilitychange",{hidden:a})}function $a(b,a,c){"Backspace"===c.key&&K(c);if(!b.$){var d=Ca.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function ab(b,a,c,d){b.$||Ba(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function bb(b){window!==window.top&&window.focus();db(b.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.xb);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),ab(b,d,c,Da),b.xb=c.buttons)}}
function fb(b,a,c){if(!b.$&&!Ba(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.xb=c.buttons;ab(b,c.type,c,Da)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function gb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function hb(b,a,c,d){const e=b.qa(),f=b.ja();b.$a=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.hb()}):10>d&&ib(b,e,f,d+1)}
function ib(b,a,c,d){-1!==b.$a&&clearTimeout(b.$a);b.$a=setTimeout(()=>hb(b,a,c,d),48)}
function Ya(b){b=b.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.bb(class extends self.eb{constructor(b){super(b,"runtime");this.Ld=!0;this.Ed=!1;this.$a=-1;this.cd="any";this.yd=this.zd=!1;this.fc=document.createElement("div");this.fc.className="c3-screen-reader-text";this.fc.setAttribute("aria-live","polite");document.body.appendChild(this.fc);this.Ha=null;this.$=!1;this.Gd="";this.Mc=-1;this.Dd=!1;this.Xc=b.qa();this.sb=b.ja();this.da=this.Cb=0;b.C("canvas","update-size",d=>{var e=this.s;e.Sc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Ld&&(e.style.display="",this.Ld=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Oa(d));b.C("runtime","raster-svg-image",d=>Pa(d));b.C("runtime","get-svg-image-size",
d=>Qa(d));b.C("runtime","set-target-orientation",d=>{this.cd=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ra(d));b.C("runtime","go-to-script",d=>Ra(d));b.C("runtime","before-start-ticking",()=>Sa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ua(this));b.C("runtime","enable-device-motion",()=>Va(this));b.C("runtime","add-stylesheet",d=>Wa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.Cc(d));b.C("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.J.style.display="";this.s.xe(d.duration)});b.C("runtime","export-to-video-progress",d=>Xa(this,d));b.C("runtime","exported-to-video",d=>{window.Ze({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Ze({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ja(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",
K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ma,{passive:!1});window.addEventListener("wheel",Ma,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Ed){var d=this.qa();var e=this.ja();if(this.s.sc()){if(this.Dd){if(this.Xc===
d&&e<this.sb){this.Cb=this.sb-e;gb(this,this.sb,this.Cb);d=void 0;break a}0<this.Cb&&(this.Cb=0,gb(this,e,this.Cb))}this.Xc=d;this.sb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.hb()});this.s.tc()&&(-1!==this.$a&&clearTimeout(this.$a),hb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>Za(this,d));window.addEventListener("webkitfullscreenerror",d=>Za(this,d));window.addEventListener("mozfullscreenerror",d=>Za(this,d));if(b.tc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ja(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Lb(!0),L(this)):"exited-fullscreen"===d?(H.Lb(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ta=new Set;this.Yb=new WeakSet;this.xa=!1}hd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ea)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},Ea);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Ka.has(a.tagName.toLowerCase())||Ja(a))&&l(this,"keyboard-blur",null,Ea)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("dblclick",a=>ab(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{bb(a);M(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{bb(a);fb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>fb(this,"pointermove",a)),window.addEventListener("mouseup",a=>fb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{bb(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.se()&&!this.s.sc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{gb(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.s.qa()}ja(){return this.s.ja()}Fc(){var b=
[...this.Ta];this.Ta.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Ta.add(a)})}ea(b){if("function"!==typeof b.play)throw Error("missing play function");this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Ta.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Ta.add(b)})}ia(b){this.Ta.delete(b);this.Yb.add(b)}Ib(b){this.xa=!!b}Cc(b){alert(b.message)}});"use strict";
async function xa(b){if(b.Se)throw Error("already initialised");b.Se=!0;var a=b.Aa.zc(("playable-ad"===b.Aa.v?b.Aa.Za:"")+"dispatchworker.js");b.Lc=await b.Aa.nc(a,b.lb,{name:"DispatchWorker"});a=new MessageChannel;b.Rc=a.port1;b.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.$c=await Aa(b)}function ya(b){return[b.Rc,b.$c]}
async function Aa(b){const a=b.Md.length;var c=b.Aa.zc(("playable-ad"===b.Aa.v?b.Aa.Za:"")+"jobworker.js");c=await b.Aa.nc(c,b.lb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Lc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Md.push(c);return e.port1}
self.ve=class{constructor(b){this.Aa=b;this.lb=b.ba;this.lb="preview"===b.v?this.lb+"workers/":this.lb+b.Za;this.Ue=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Md=[];this.$c=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.wa({jf:!0,kf:"workermain.js",ab:["scripts/c3runtime.js"],kc:[],fd:"",ff:"scripts/",lc:[],Zd:"html5"}));"use strict";const jb=180/Math.PI;
async function kb(b,a){if(a.isiOSCordova||a.isSafari)b.bc=!0;b.dd=a.timeScaleMode;b.Rd=["equalpower","HRTF","soundfield"][a.panningModel];b.Cd=["linear","inverse","exponential"][a.distanceModel];b.Sd=a.refDistance;b.Qd=a.maxDistance;b.Ud=a.rolloffFactor;if(b.s.Sc)b.bc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Fd)});else{var c={latencyHint:a.latencyHint};b.Xd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");lb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&lb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.fa);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function mb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,p=a.pos,q=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Nd=g.slice(0);nb(b,g);try{b.R=await ob(b,c,d,e,g,f);if(q){P(b.R,!0);var r=b.R,D=q.innerAngle,oa=q.outerAngle,pa=q.outerGain;if(r.qb){pb(r,q.x,q.y,q.z,q.angle);var G=self.cb.ye;r.ta[0]!==G(D)&&
(r.ta[0]=G(D),r.F.coneInnerAngle=G(D));r.ta[1]!==G(oa)&&(r.ta[1]=G(oa),r.F.coneOuterAngle=G(oa));r.ta[2]!==pa&&(r.ta[2]=pa,r.F.coneOuterGain=pa)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof C&&0!==C?(Q(b.R,!0),qb(b.R,C)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,p,z)}catch(Eb){console.error("[Construct] Audio: error starting playback: ",Eb);return}finally{c=g.join(" ");d=b.zb.get(c);if(!d)throw Error("expected pending tag");d.gd--;0===d.gd&&(d.resolve(),b.zb.delete(c))}u(b)}
async function rb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await sb(b,c);for(const h of R(b,c))if(!h.Ra){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Qa=g;h.Wd=a}S(b)}async function tb(b,a){const c=a.tags;a=a.rate;await sb(b,c);for(const d of R(b,c))d.na!==a&&(d.na=a,d.Fa())}async function ub(b,a){const c=a.tags;a=a.pos;await sb(b,c);for(const d of R(b,c))d.uc(a)}
async function vb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ob(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function wb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function xb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ee(b,...e);else if("delay"===c)d=new self.ce(b,...e);else if("convolution"===c){var g=d=new self.be(b,f.ka,...e),h=a.bufferType;g.Ad=a.bufferOriginalUrl;g.Bd=h}else if("flanger"===c)d=new self.fe(b,...e);else if("phaser"===
c)d=new self.he(b,...e);else if("gain"===c)d=new self.ge(b,...e);else if("stereopan"===c)d=new self.je(b,...e);else if("tremolo"===c)d=new self.ke(b,...e);else if("ringmod"===c)d=new self.ie(b,...e);else if("distortion"===c)d=new self.de(b,...e);else if("compressor"===c)d=new self.ae(b,...e);else if("analyser"===c)d=new self.$d(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let p=g.ma.get(h);p||(p=[],g.ma.set(h,p));d.Kd=p.length;d.bd=h;p.push(d);yb(g,h)}zb(b)}
async function Ab(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ca()&&1===c||!e.Ca()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ma.values())for(const g of f)g.j();b.ma.clear();b.ic=a.timeScale;b.Nc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.fa[e]=d[e];b.g.listener.setOrientation(...b.fa)}b.xa=a.isSilent;b.s.Ib(b.xa);b.Xb=a.masterVolume;b.Oa.gain.value=
b.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>xb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Bb(b,f,c)));S(b)}
async function Cb(b,a){try{const c=b.g.suspend(a.time);b.Jd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.Gb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Db(d)),b.Jd=!0);await c}catch(c){Db(c)}}
function lb(b){b.Rb||(b.Qc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Rb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.la)if(g.gb()===c)return await Fb(g),g;if(f)return null;if(e&&(b.bc||b.Id)){f=0;for(let h=0,k=b.la.length;h<k;++h)g=b.la[h],b.la[f]=g,g.Ca()?g.j():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.Xd;e&&f&&(b.Id=!0);c=!e||b.bc||f?new self.ne(b,a,c,d,e,f):new self.le(b,a,c,d,e);b.la.push(c);await Fb(c);b.Pd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Pd.add(a));return c}
function Gb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Hb(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].N():b.pa()}function yb(b,a){a=a.toLowerCase();let c=b.pa();var d=b.ma.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.pa()):e.U(d[f+1].N())}}for(const f of Ib(b,a))d=c,e=f.ga||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Yc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Ib(b,a){if(a)for(const c of b.H)Gb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Jb(b,a,c){return c?b.s.Re(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Kb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Gb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ob(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.mc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ic?new self.me(a.u,a,e):new self.oe(a.u,a,e);b.H.push(e);return e}
function nb(b,a){a=a.join(" ");let c=b.zb.get(a);if(!c){let d=null;c={gd:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.gd++}function sb(b,a){return(b=b.zb.get((0===a.length?b.Nd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Na.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Lb(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function zb(b){b.Tc||(b.Tc=!0,Promise.resolve().then(()=>Mb(b)))}
function Mb(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.fb());l(b,"fxstate",{fxstate:a});b.Tc=!1}
async function Bb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ob(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],f=d.orient,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],e.setPosition(...b.Va),e.setOrientation(...b.Ua),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),qb(b,d));c.Play(k,p,q,0);a.isPlaying||c.ib();c.Bc(a)}}}function Db(b){console.error("[Audio] Offline rendering error: ",b)}
self.cb=class extends self.eb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Rb=this.Qc=!1;this.Ba=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Rb&&(this.Qc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Rb=!1)}};this.la=[];this.H=[];this.R=null;this.Nd=[];this.Pd=new Set;this.Od=-1;this.zb=new Map;this.Xb=1;this.xa=!1;this.dd=0;this.ic=1;this.Nc=0;this.Rd="HRTF";this.Cd="inverse";this.Sd=600;this.Qd=1E4;this.Ud=1;this.aa=[0,0,0];this.fa=[0,0,-1,0,1,0];this.Id=this.bc=!1;this.Xd=this.s.te();this.ma=new Map;this.Na=new Set;this.Jd=this.Tc=!1;this.Yc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Yc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Hb(this,this.Yc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Oa.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>kb(this,a)],["play",a=>mb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Da()}],["stop-all",()=>{for(const a of this.H)a.Da()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.ib():d.Hb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>rb(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Oa.gain.value=this.Xb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Nb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.s.Ib(this.xa);for(const c of this.H)c.Mb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.vc(a)}],["set-playback-rate",a=>tb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),qb(d,a)}],["seek",a=>ub(this,a)],["preload",a=>vb(this,a)],["unload",a=>wb(this,a)],["unload-all",()=>{for(const a of this.la)a.j();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.wc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>xb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ma.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);zb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ma.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ma.delete(a);yb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Nc=a.gameTime;this.Od=a.tickCount;if(0!==this.dd)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.fa[0]!==
c[0]||this.fa[1]!==c[1]||this.fa[2]!==c[2]||this.fa[3]!==c[3]||this.fa[4]!==c[4]||this.fa[5]!==c[5])){for(let d=0;6>d;++d)this.fa[d]=c[d];this.g.listener.setOrientation(...this.fa)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&pb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Ab(this,a)],["offline-render-audio",a=>Cb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}pa(){return this.Oa}Fb(){return this.xa}ea(b){this.s.ea(b)}ia(b){this.s.ia(b)}Ea(){for(var b of this.Na)b.Ea();
b=this.g.currentTime;for(var a of this.H)a.Ea(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());l(this,"state",{tickCount:this.Od,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.bd,index:c.Kd,peak:c.Wa,rms:c.Td,binCount:c.l.frequencyBinCount,freqBins:c.Hd}))});0===a.length&&0===this.Na.size&&aa(this)}static ye(b){return b*jb}static nd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static we(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.wa.bb(self.cb);"use strict";function Fb(b){b.Vb||(b.Vb=b.Ac());return b.Vb}self.jd=class{constructor(b,a,c,d,e){this.u=b;this.We=a;this.Ja=c;this.T=d;this.Te=e;this.Ic="";this.Vb=null}j(){this.Vb=this.u=null}Ac(){}W(){return this.u.W()}pc(){return this.We}gb(){return this.Ja}oc(){return this.T}Ca(){return this.Te}ha(){}};"use strict";
self.le=class extends self.jd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.W().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.W().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Kb(this.u,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Ac(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ja})}V(){return this.M}ha(){return this.M.duration}};"use strict";
async function Ob(b){if(b.Ga)return b.Ga;var a=b.u.s;if("cordova"===a.v&&a.pd(b.Ja)&&a.Tb)b.Ga=await a.Eb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Pb(b){if(b.ka)return b.ka;b.ka=await Jb(b.u,b.Ga,b.Ve);b.Ga=null}
self.ne=class extends self.jd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.ka=this.Ga=null;this.Ve=!!f}j(){Kb(this.u,this);this.ka=this.Ga=null;super.j()}async Ac(){try{await Ob(this),await Pb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ha(){return this.ka?this.ka.duration:0}};"use strict";let Qb=0;
function P(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(Q(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.u.Rd,b.F.distanceModel=b.u.Cd,b.F.refDistance=b.u.Sd,b.F.maxDistance=b.u.Qd,b.F.rolloffFactor=b.u.Ud),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.pa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.pa())))}
function Q(b,a){a=!!a;b.Ub!==a&&(b.Ub=a,b.Ub?(P(b,!1),b.ga=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ga),b.ga.connect(b.pa())):(b.ga.disconnect(),b.ga=null,b.G.disconnect(),b.G.connect(b.pa())))}function qb(b,a){b.Ub&&b.ad!==a&&(b.ga.pan.value=a,b.ad=a)}function T(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Qa=-1;b.G.gain.value=b.qc()}function Nb(b,a){a=!!a;b.Ra!==a&&(b.Ra=a,b.Mb())}
function pb(b,a,c,d,e){if(b.qb){var f=b.Va,g=b.Ua,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Vc?b.u.Nc:performance.now()/1E3}
self.kd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Nb=Qb++;this.G=this.W().createGain();this.G.connect(this.pa());this.F=null;this.qb=!1;this.Va=[0,0,0];this.Ua=[0,0,0];this.ta=[0,0,0];this.ga=null;this.Ub=!1;this.ad=0;this.I=!0;this.Y=this.ua=this.K=!1;this.Ka=1;this.Ra=!1;this.na=1;b=this.u.dd;this.Vc=1===b&&!this.Ca()||2===b;this.Qa=this.ra=-1;this.Wd=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ga&&(this.ga.disconnect(),this.ga=null);this.G.disconnect();
this.G=null}W(){return this.u.W()}pa(){return Hb(this.u,0<this.oa.length?this.oa[0]:"")}pc(){return this.P.pc()}gb(){return this.P.gb()}oc(){return this.P.oc()}Ca(){return this.P.Ca()}O(){}mc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}La(){}ha(){return this.P.ha()}Play(){}Da(){}ib(){}Hb(){}Ea(b){-1!==this.Qa&&b>=this.Qa&&(this.Qa=-1,this.Wd&&this.Da(),Lb(this.u,"fade-ended",this.oa,this.Nb))}qc(){const b=this.Ka;return isFinite(b)?b:0}Fb(){return this.u.Fb()}Mb(){}vc(){}Fa(){}uc(){}wc(){}rc(){}fb(){var b=
this.Nb,a=this.oa,c=this.ha(),d=-1===this.Qa?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Va,orient:this.Ua,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.na,uid:this.ra,bufferOriginalUrl:this.pc(),bufferUrl:"",bufferType:this.oc(),isMusic:this.Ca(),isLooping:this.Y,isMuted:this.Ra,resumePosition:this.rc(),pan:f,stereoPan:this.ga?
this.ad:null}}Bc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Fa());Nb(this,b.isMuted)}};"use strict";
self.me=class extends self.kd{constructor(b,a,c){super(b,a,c);this.P.yb.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Da();this.P.yb.disconnect();super.j()}V(){return this.P.V()}Dc(){this.I=!0;this.ra=-1;Lb(this.u,"ended",this.oa,this.Nb)}O(){return this.V().ended}mc(){return this.I?!0:this.O()}La(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.u.ea(d);this.K=this.I=!1;this.Y=b;this.na=1}Da(){const b=this.V();b.paused||b.pause();this.u.ia(b);this.I=!0;this.K=!1;this.ra=-1}ib(){if(!(this.K||this.I||this.O())){var b=this.V();b.paused||b.pause();this.u.ia(b);this.K=!0}}Hb(){!this.K||this.I||this.O()||(this.u.ea(this.V()),this.K=!1)}Mb(){this.V().muted=this.Ra||this.Fb()}vc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Fa(){let b=this.na;this.Vc&&(b*=this.u.ic);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}uc(b){if(!this.I&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}rc(){return this.La()}wc(b){b?this.IsPlaying()?(this.V().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.u.ea(this.V()),this.ua=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.jb=null}
self.oe=class extends self.kd{constructor(b,a,c){super(b,a,c);this.o=null;this.$b=d=>this.Dc(d);this.Pc=!0;this.jb=null;this.S=this.ac=this.cc=0;this.Zc=1}j(){this.Da();V(this);this.$b=null;super.j()}Dc(b){this.K||this.ua||b.target!==this.jb||(this.I=this.Pc=!0,this.ra=-1,V(this),Lb(this.u,"ended",this.oa,this.Nb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Pc}mc(){return!this.o||this.I?!0:this.O()}La(){let b;b=this.K?this.S:this.ac+(U(this)-this.cc)*this.na;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Zc=1;T(this,a);V(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ka;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.$b;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Pc=!1;this.Y=b;this.na=1;this.cc=U(this);this.ac=c}Da(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.ra=-1}ib(){this.K||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.I||this.O()||(V(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,T(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.cc=U(this),this.ac=this.S,this.K=!1)}qc(){return super.qc()*this.Zc}Mb(){this.Zc=this.Ra||this.Fb()?0:1;T(this,this.Ka)}vc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Fa(){let b=this.na;this.Vc&&(b*=this.u.ic);this.o&&(this.o.playbackRate.value=b)}uc(b){this.I||this.O()||(this.K?this.S=b:(this.ib(),this.S=
b,this.Hb()))}rc(){return this.S}wc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.La(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ua=!1:this.ua&&(V(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,T(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.cc=U(this),this.ac=this.S,this.ua=!1)}Bc(b){super.Bc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.W();this.Kd=-1;this.T=this.bd="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.bd,params:this.m}}}
self.ee=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.ce=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.vb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ob=W(this);this.ob.gain.value=c;this.A.connect(this.vb);this.A.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.X);this.X.connect(this.ob);this.ob.connect(this.vb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.X.disconnect();this.ob.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.cb.nd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.ob.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.be=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Bd=this.Ad="";this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.nb=this.g.createConvolver();this.nb.normalize=c;this.nb.buffer=a;this.A.connect(this.nb);this.A.connect(this.h);this.nb.connect(this.i)}j(){this.A.disconnect();this.nb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.Ad;b.bufferUrl="";b.bufferType=this.Bd;return b}};
self.fe=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.pb=W(this);this.pb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.pb);this.pb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.pb.gain,a/100,c,d)}}};
self.he=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,c,d)}}};self.ge=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.cb.nd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.je=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.ke=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.ie=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Bb=W(this);this.Bb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Bb.gain);this.B.start(0);this.A.connect(this.Bb);this.A.connect(this.h);this.Bb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Bb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.de=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=W(this);this.ec=W(this);this.dc=W(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.jc.curve=this.Jc;this.A.connect(this.ec);this.A.connect(this.h);this.ec.connect(this.jc);this.jc.connect(this.dc);this.dc.connect(this.i)}j(){this.A.disconnect();this.ec.disconnect();this.jc.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ae=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.$d=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Hd=new Float32Array(this.l.frequencyBinCount);this.Vd=new Uint8Array(a);this.Td=this.Wa=0;b=this.u;b.Na.add(this);S(b)}j(){this.u.Na.delete(this);this.l.disconnect();super.j()}Ea(){this.l.getFloatFrequencyData(this.Hd);this.l.getByteTimeDomainData(this.Vd);const b=this.l.fftSize;let a=this.Wa=0;for(var c=0;c<b;++c){let d=(this.Vd[c]-
128)/128;0>d&&(d=-d);this.Wa<d&&(this.Wa=d);a+=d*d}c=self.cb.we;this.Wa=c(this.Wa);this.Td=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Rb(b,a){a=a.type;let c=!0;0===a?c=await Sb():1===a&&(c=await Tb());l(b,"permission-result",{type:a,result:c})}
async function Sb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Tb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.wa.bb(class extends self.eb{constructor(b){super(b,"touch");n(this,"request-permission",a=>Rb(this,a))}});"use strict";
async function Ub(b,a){b.Uc=a.isInWorker;a=document.createElement("video");b.hc=!!a.requestVideoFrameCallback&&!b.s.sc();const c=!!self.createImageBitmap;b.Ab=b.Uc||c;return{postImageBitmaps:b.Ab,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Vb(b,a){if(!b.Kc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Vb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Kc.has(a)||v(b,"playback-event",c,{type:d})}
self.wa.bb(class extends self.qe{constructor(b){super(b);this.Ab=this.hc=this.Uc=this.kb=!1;this.Zb=this.Ye=0;this.Kc=new WeakSet;n(this,"init",a=>Ub(this,a));w(this,"play",a=>{this.ea(a)});w(this,"pause",a=>{this.ia(a);a.pause()});w(this,"set-source",(a,c)=>{a.src=c.src;a.load()});w(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});w(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});w(this,"set-looping",(a,c)=>{a.loop=c.isLooping});w(this,"set-muted",(a,c)=>{a.muted=c.isMuted});w(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>x(this,a)}ea(b){this.s.ea(b);this.Ab&&this.hc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Vb(this,b)))}ia(b){this.s.ia(b);this.Ab&&this.hc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}md(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ea(c);this.Zb++;u(this);return c}rd(){}od(b){this.ia(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.Zb=Math.max(this.Zb-1,0);0===this.Zb&&aa(this);this.Kc.add(b)}Ea(){const b={},a={sequenceNumber:this.Ye++,videoData:b},c=[],d=[];for(const [e,f]of this.Pa.entries()){const g=f.Qb,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Ab)if(this.hc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.Uc?l(this,"state",a,!1,c):m(this,"state",a)})}});"use strict";function Wb(){}function Xb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>l(b,"sw-message",a.data))}
function Yb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.wa.bb(class extends self.eb{constructor(b){super(b,"browser");this.v="";t(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Xb(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Yb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.qf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.v||"macos-wkwebview"===this.v)self.wa.Lb(!0),this.s.Hc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Wb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.v||"macos-wkwebview"===
this.v)self.wa.Lb(!1),this.s.Hc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Wb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=
Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),
c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{l(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{l(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{l(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{l(this,"backbutton")})}Cc(b){alert(b.message)}Ec(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
